FROM registry.suse.com/bci/golang:1.25

ARG DAPPER_HOST_ARCH
ENV ARCH $DAPPER_HOST_ARCH

RUN zypper -n rm container-suseconnect && \
    zypper -n install git curl docker gzip tar wget awk

## install golangci-lint
# /go/bin 또는 /usr/local/bin 등 기존 실행 경로에 덮어쓰도록 설정합니다.
RUN if [ "${ARCH}" = "amd64" ]; then \
    curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.64.5; \
    fi

ENV DAPPER_ENV REPO TAG DRONE_TAG CROSS
ENV DAPPER_SOURCE=/go/src/github.com/harvester/docker-machine-driver-harvester
ENV DAPPER_OUTPUT ./bin ./dist
ENV DAPPER_DOCKER_SOCKET true
ENV HOME ${DAPPER_SOURCE}

WORKDIR ${DAPPER_SOURCE}
ENTRYPOINT ["./scripts/entry"]
CMD ["ci"]
