name: CI Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 릴리스 생성을 위한 쓰기 권한 추가

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          make

      - name: Upload artifacts
        if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/master')
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ./dist/artifacts/*

      - name: Get code info
        id: info
        run: |
          source scripts/version
          echo "artifacts_dir=${PWD}/dist/artifacts" >> $GITHUB_OUTPUT
          echo "version=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT
          echo "base_version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Generate release info
        if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/master')
        env:
          BASE_VERSION: ${{ steps.info.outputs.base_version }}
        run: |
          echo "🍻" > release.txt

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ github.ref_name }} --draft --notes "Draft release for ${{ github.ref_name }}"
          gh release upload ${{ github.ref_name }} ${{ steps.info.outputs.artifacts_dir }}/*

